VERSION := 3.0

ORION_BUILDTYPE ?= UNOFFICIAL

ORION_VERSION := OrionOS-$(VERSION)-$(TARGET_DEVICE)-$(ORION_BUILDTYPE)-$(shell date +%Y%m%d)

PRODUCT_PROPERTY_OVERRIDES += \
    ro.orion.version=$(ORION_VERSION) \
    ro.orion.buildtype=$(ORION_BUILDTYPE)
